apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: fekuna/ticketing-auth
      context: auth
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
      docker:
        dockerfile: Dockerfile
    - image: fekuna/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.js'
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
